language: c++
dist: trusty
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq  libsndfile-dev libsdl-sound1.2-dev
script:
  - mkdir build && cd build && cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . 

